### ISSUE TITLE
Problem after estimating principal components

### ISSUE THREAD

**Issue by blackhill86** [PcAux-Package/PcAux#13] opened 2017-06-24 21:43 UTC
After estimating the principal components I get the following error when trying to impute the data:
```R
Multiply imputing missing data...
--Constructing predictor matrix...Error in `[<-`(`*tmp*`, , predVars, value = 1) : subscript out of bounds
```
These are my lines to create the pcaux:
```R 
pcAuxOut <- createPcAux(cleanData,
                      nComps = c(.6,.2),
                      maxPolyPow =  3L,
                      interactType = 0,
                      mySeed = 235711L,
                      verbose = 2,
                      doImputation = TRUE,
                      castData = FALSE
                      )
```
And these are my lines to impute the data:

```R
miOut <- miWithPcAux(rawData = dat1,
                     pcAuxData = pcAuxOut,
                     nImps = 100,
                     nProcess = 3L)
```

I believe the problem is related to the number of moderators , because in this run I'm not estimating any interaction. 

Thanks for your help!

**Comment by kylelang** [comment] 2017-09-26 11:58
Does this issue still occur with the latest stable release? 

I am unable to reproduce the error you're describing using the iris2 dataset. If you are still experiencing this issue, can you provide a minimally sufficient example to elicit the error?

Thanks!

**Comment by blackhill86** [comment] 2017-11-01 17:00
I'm attaching a minimal example.  Maybe you already fixed it in the last version I haven't checked yet. 

[sampleData.zip](https://github.com/PcAux-Package/PcAux/files/1434968/sampleData.zip)

**Comment by kylelang** [comment] 2017-11-02 10:48
Come on, man. This cannot be a minimal example. Do you really need 221 ordinal variables and 49 nominal variables to trigger this bug? Please run this yourself and see what happens with the latest version of PcAux.

**Comment by ppanko** [comment] 2018-08-14 18:33
Looking back on this issue, it looks like the error might be the product of re-running one of the PcAux functions on a pcAuxData object that is already modified by the same or a later function. For completeness sake, I think we can close this issue and revisit it if this error resurfaces.

**Comment by kylelang** [comment] 2018-08-17 13:47
@ppanko, sounds good. Thanks!

**Closed as completed by kylelang** 2018-08-17 13:47 UTC
